name: Python Flask CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Connect to server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: 192.168.1.27
        username: serveur
        port: 22
        password: admin123


    - name: Clone repository on server
      run: |
        git@github.com:Taikoz/flask-sl00x-skeleton-auth.git
        cd /home/serveur/Bureau/flask-sl00x-skeleton-auth

    - name: Install dependencies on server
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build and run application on server
      run: |
        docker-compose up -d
        
    - name: Run App
      run: |
        python3 app.py

    - name: Wait for application to start
      run: |
        while ! curl -s http://localhost:5000; do
          sleep 5
        done
        
    - name: Tear down application on server
      run: |
        docker-compose down


 
